name: egg_timer
description: A cute, scalable egg timer app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management (scalable, testable)
  flutter_riverpod: ^2.5.1

  # Routing (optional now, useful as app grows)
  go_router: ^14.2.0

  # SVG support (perfect for Figma exports)
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  image_path: "assets/icon/app_icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/illustrations/
