name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          version: "stable"
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/*.aab

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          version: "stable"
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Build iOS IPA
        run: flutter build ipa --release

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
